In [6]:
# Step 1: Import necessary libraries
import pandas as pd
import numpy as np  # For handling numerical data
import matplotlib.pyplot as plt  # For data visualization
from sklearn.linear_model import LinearRegression  # For building the regression model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score  # For evaluating the model
from sklearn.preprocessing import PolynomialFeatures
import statsmodels.api as sm  # For OLS (Ordinary Least Squares) Regression

In [7]:
data = {
    'Size': [1500, 1600, 1700, 1800, 1900, 2000, 2100, 2200],
    'Bedrooms': [3, 3, 3, 4, 4, 4, 5, 5],
    'Age': [10, 15, 10, 20, 30, 15, 20, 25],
    'Price': [300000, 320000, 340000, 360000, 400000, 370000, 420000, 430000]
}
df=pd.DataFrame(data)
df

   Size  Bedrooms  Age   Price
0  1500         3   10  300000
1  1600         3   15  320000
2  1700         3   10  340000
3  1800         4   20  360000
4  1900         4   30  400000
5  2000         4   15  370000
6  2100         5   20  420000
7  2200         5   25  430000

In [11]:
# Define independent variables (features) and dependent variable (target)
X = df[['Size', 'Bedrooms', 'Age']]  #  3 Independent variables
y = df['Price']  # Dependent variable
 
# X = df[['Size', 'Bedrooms']]  #  2 Independent variables
# y = df['Price']  # Dependent variable
 
#X = df[['Size']]  #  1 Independent variables
#y = df['Price']  # Dependent variable
 
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
 
# Create a linear regression model
model = LinearRegression()
 
# Train the model
model.fit(X_train, y_train)
 
# Make predictions on the test set
y_pred = model.predict(X_test)
 
# Coefficients and intercept
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
 
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
 
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Intercept: 33576.01713061816
Coefficients: [  182.01284797 -6252.67665953  1391.86295503]
Mean Squared Error: 299314729.30776143
R-squared: 0.5210964331075817

In [13]:
new_house = np.array([[1500,3,10]])
predicted_price = model.predict(new_house)
print(f"Predicted Price for new house: {predicted_price[0]}")

Predicted Price for new house: 301755.888650963

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [14]:
new_house = pd.DataFrame([[1500, 3, 10]], columns=['Size', 'Bedrooms', 'Age'])

# Predict the price
predicted_price = model.predict(new_house)
print(f"Predicted Price for new house: {predicted_price[0]}")

Predicted Price for new house: 301755.888650963

**Multipile_linear_regression(wine dataset)**

In [23]:
 import pandas as pd
data=pd.read_csv("Wine.csv")
data.head()

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [37]:
# Define independent variables (features) and dependent variable (target)

#X = data[['Alcohol','Malic.acid','Ash','Acl','Mg','Phenols','Flavanoids','Nonflavanoid.phenols','Proanth','Color.int','Hue','OD','Proline']]  #  14 Independent variables
#y = data['Wine']  # Dependent variable

X = data[['Alcohol','Malic.acid','Ash','Acl','Mg','Phenols','Flavanoids','Nonflavanoid.phenols','Proanth','Color.int','Hue','OD']]#13 independent variables
y = data['Wine']  # Dependent variable

#X = data[['Alcohol','Malic.acid','Ash','Acl','Mg']]  #  5 Independent variables
#y = data['Wine']  # Dependent variable

#X = data[['Alcohol','Malic.acid','Ash','Acl',]]  #  5 Independent variables
#y = data['Wine']  # Dependent variable

#X = data[['Alcohol','Malic.acid','Ash','Acl']]  # 4 Independent variables
#y = data['Wine']  # Dependent variable

#X = data[['Alcohol','Malic.acid','Ash',]]  # 3 Independent variables
#y = data['Wine']  # Dependent variable

#X = data[['Alcohol','Malic.acid',]]  #  2 Independent variables
#y = data['Wine']  # Dependent variable

#X = data[['Alcohol']]  #  5 Independent variables
#y = data['Wine']  # Dependent variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
 
# Create a linear regression model
model = LinearRegression()
 
# Train the model
model.fit(X_train, y_train)
 
# Make predictions on the test set
y_pred = model.predict(X_test)
 
# Coefficients and intercept
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)
 
# Evaluate the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
 
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Intercept: 5.280250579743492
Coefficients: [-0.18895848  0.05675354 -0.37091393  0.06468283 -0.00201323  0.14300509
 -0.36654111 -0.27543685  0.01462343  0.05847918 -0.18656249 -0.3133033 ]
Mean Squared Error: 0.09247532495228503
R-squared: 0.8414708715103685

In [38]:
new_house = pd.DataFrame([[14.23,1.71,2.43,15.6,127,2.65,2.76,0.28,2.29,5.64,1.04,3.92]], columns=['Alcohol','Malic.acid','Ash','Acl','Mg','Phenols','Flavanoids','Nonflavanoid.phenols','Proanth','Color.int','Hue','OD'])
# Predict the price
predicted_price = model.predict(new_house)
print(f"Predicted Price for new house: {predicted_price[0]}")

Predicted Price for new house: 0.7717955669370076